### ISSUE TITLE
Add a [needs-review] label when commenting with ♻️

### ISSUE THREAD

**Issue by Knack** [balvig/cp-8#9]
Just an idea, but I'd like the recycle symbol to explicitly tell others that a PR needs to be reviewed.

- Currently, ♻️ just removes any [**reviewed**] label if present.

My idea is:

- Commenting with ♻️ will remove [**reviewed**] and add [**needs-review**]
- Adding [WIP] to the subject will remove both [**reviewed**] and [**needs-review**]
- Commenting with 👍  will add [**reviewed**] and remove [**needs-review**]

The text "needs-review" was inspired by the [Atom project](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#pull-request-labels) but you can choose another label.

I can work in a PR if you think is a good idea. It's Friday! 😄

**Comment by balvig** [comment]
Hey @Knack! 

Sounds like it could be useful, but also thinking maybe it's hard to know when to _remove_ `needs-review` beyond what we can automate above. For example, if I review a PR, should I manually remove the label after that to signify that the PR no longer needs more reviews? etc. 

Anyway, will keep thinking about it, thanks for sharing the idea (and offering to work on it!) 😄
